Repository AppCenter-Snaptime/snaptime-iOS, pull requests merged in 2024-05, with the labels that each got.

#19 [Feat] 프로필 네트워크 로직 구현
  snaptime/Podfile
  snaptime/Podfile.lock
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime.xcodeproj/xcshareddata/xcschemes/Snaptime.xcscheme
  snaptime/Snaptime/Coordinator/AuthCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Info.plist
  snaptime/Snaptime/Profile/APIService/ProfileAPI.swift
  snaptime/Snaptime/Profile/Model/ProfileBasicModel.swift
  snaptime/Snaptime/Profile/Model/Token.swift
  snaptime/Snaptime/Profile/Model/UserAlbumManager.swift
  snaptime/Snaptime/Profile/Model/UserAlbumModel.swift
  snaptime/Snaptime/Profile/Model/UserProfileCountManager.swift
  snaptime/Snaptime/Profile/Model/UserProfileCountModel.swift
  snaptime/Snaptime/Profile/Model/UserProfileManager.swift
  snaptime/Snaptime/Profile/Model/UserProfileModel.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/MyProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumAndTagListView.swift
  snaptime/Snaptime/Profile/View/AlbumListView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/AlbumListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileListTabButton.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileStatusButton.swift
  snaptime/Snaptime/Profile/View/CustomComponents/SettingTableViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/TagListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Profile/View/TagListView.swift
  snaptime/Snaptime/SceneDelegate.swift
Labels: ✨ new feature, Bowon 🙋🏻‍♀️

#20 [Feat] 메인 앨범 뷰 네트워크 로직 작성
  snaptime/Podfile
  snaptime/Podfile.lock
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Components/AccessToken.swift
  snaptime/Snaptime/Components/SnapCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/AppCoordinator.swift
  snaptime/Snaptime/Home/Model/Album.swift
  snaptime/Snaptime/Home/Model/AlbumSnapResDto.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
Labels: ✨ new feature, Daehyun 🙋🏻‍♂️

#21 [Fix] Snap에 해당하는 UI 수정
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Community/VCs/NotificationViewController.swift
  snaptime/Snaptime/Community/View/NotificationCollectionViewCell.swift
  snaptime/Snaptime/Components/AccessToken.swift
  snaptime/Snaptime/Components/AlbumCollectionViewCell.swift
  snaptime/Snaptime/Components/SnapCollectionViewCell.swift
  snaptime/Snaptime/Components/SnapPreviewCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Home/VCs/AlbumDetailViewController.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Home/VCs/SnapListViewController.swift
  snaptime/Snaptime/Home/View/AlbumSnapCollectionViewCell.swift
  snaptime/Snaptime/Profile/VCs/MyProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumAndTagListView.swift
  snaptime/Snaptime/Profile/View/AlbumListView.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Recommend/View/RecommendSectionView.swift
  snaptime/Snaptime/community/View/CommunityCollectionViewCell.swift
  snaptime/Snaptime/community/View/UserPostView.swift
Labels: 📋 UI, Bowon 🙋🏻‍♀️

#24 [Feat] 커뮤니티 네트워크 로직 구현
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Community/Model/CommunitySnapManager.swift
  snaptime/Snaptime/Community/Model/CommunitySnapModel.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/AccessToken.swift
  snaptime/Snaptime/Components/SnapCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Home/VCs/SnapListViewController.swift
  snaptime/Snaptime/Profile/Model/UserProfileManager.swift
Labels: ✨ new feature, Bowon 🙋🏻‍♀️
