Repository AppCenter-Snaptime/snaptime-iOS, pull requests merged in 2024-07, with the labels that each got.

#29 [Feat] 댓글 화면 UI 수정 & 네트워크 로직 작성
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Comment/View/CommentCollectionViewCell.swift
  snaptime/Snaptime/Comment/View/CommentSupplementaryHeaderView.swift
  snaptime/Snaptime/Comment/View/SingleCommentView.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/RoundImageView.swift
  snaptime/Snaptime/Components/SnapCollectionViewCell.swift
  snaptime/Snaptime/Components/SnapViewController.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Extension/UITextField+.swift
  snaptime/Snaptime/Home/Model/Album.swift
  snaptime/Snaptime/Home/Model/FindSnapResDto.swift
Labels: ✨ new feature, 📋 UI, Daehyun 🙋🏻‍♂️

#28 [Feat] 프로필 설정 정보 fetch & 수정 네트워크 로직 구현
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/AppDelegate.swift
  snaptime/Snaptime/Community/Model/CommunitySnapManager.swift
  snaptime/Snaptime/Community/Model/CommunitySnapModel.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/AccessToken.swift
  snaptime/Snaptime/Components/Model/SnapResDTO.swift
  snaptime/Snaptime/Components/SnapCollectionViewCell.swift
  snaptime/Snaptime/Components/SnapPreviewCollectionViewCell.swift
  snaptime/Snaptime/Components/SnapPreviewViewController.swift
  snaptime/Snaptime/Components/SnapViewController.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Profile/Model/ProfileBasicModel.swift
  snaptime/Snaptime/Profile/Model/UserAlbumManager.swift
  snaptime/Snaptime/Profile/Model/UserAlbumModel.swift
  snaptime/Snaptime/Profile/Model/UserProfileCountManager.swift
  snaptime/Snaptime/Profile/Model/UserProfileCountModel.swift
  snaptime/Snaptime/Profile/Model/UserProfileCountResponse.swift
  snaptime/Snaptime/Profile/Model/UserProfileInfoRequest.swift
  snaptime/Snaptime/Profile/Model/UserProfileInfoResponse.swift
  snaptime/Snaptime/Profile/Model/UserProfileManager.swift
  snaptime/Snaptime/Profile/Model/UserProfileModel.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/CustomComponents/AlbumListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/EditProfileTextField.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileSettingItemView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileSettingView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/SettingTableViewCell.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Recommend/VCs/RecommendViewController.swift
Labels: ✨ new feature, 🧑🏻‍🔧 refactoring, Bowon 🙋🏻‍♀️

#31 [Feat] CommentViewController 댓글 api 적용
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Comment/View/CommentCollectionViewCell.swift
  snaptime/Snaptime/Comment/View/CommentSupplementaryFooterView.swift
  snaptime/Snaptime/Comment/View/CommentSupplementaryHeaderView.swift
  snaptime/Snaptime/Comment/View/SingleCommentView.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/SnapCollectionViewCell.swift
  snaptime/Snaptime/Components/SnapViewController.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Extension/String+.swift
  snaptime/Snaptime/Model/AddParentReplyReqDto.swift
  snaptime/Snaptime/Model/ChildReplyInfo.swift
  snaptime/Snaptime/Model/CommonResponseDtoFindChildReplyResDto.swift
  snaptime/Snaptime/Model/CommonResponseDtoListFindParentReplyResDto.swift
  snaptime/Snaptime/Model/FindChildReplyResDto.swift
  snaptime/Snaptime/Model/FindParentReplyResDto.swift
  snaptime/Snaptime/Model/ParentReplyInfo.swift
Labels: ✨ new feature, 📋 UI, Daehyun 🙋🏻‍♂️

#33 [Feat] 네트워크 로직 및 Custom Alert UI 추가
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/VCs/BaseViewController.swift
  snaptime/Snaptime/Components/VCs/CustomAlertViewController.swift
  snaptime/Snaptime/Components/Views/SnapCollectionViewCell.swift
  snaptime/Snaptime/Model/AccessToken.swift
  snaptime/Snaptime/Model/CommonResDtoVoid.swift
  snaptime/Snaptime/Model/CommonResponseDtoListFindSnapPagingResDto.swift
  snaptime/Snaptime/Model/CommonResponseDtoListProfileTagSnapResDto.swift
  snaptime/Snaptime/Model/FindFriendResDto.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/FollowViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumListView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileListTabButton.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileStatusButton.swift
  snaptime/Snaptime/Profile/View/CustomComponents/TagListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/FollowTableViewCell.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Profile/View/TagListView.swift
  snaptime/Snaptime/Profile/View/TopTapBarView.swift
Labels: ✨ new feature, 📋 UI, Bowon 🙋🏻‍♀️

#35 [Feat] 메인화면 기능 추가
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/VCs/SnapPreviewViewController.swift
  snaptime/Snaptime/Components/VCs/SnapViewController.swift
  snaptime/Snaptime/Components/Views/SnapCollectionViewCell.swift
  snaptime/Snaptime/Components/Views/SnapPreviewCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Home/VCs/QRReaderViewController.swift
  snaptime/Snaptime/Model/CommonResponseDtoListFindSnapPagingResDto.swift
  snaptime/Snaptime/Model/FindAlbumResDto.swift
  snaptime/Snaptime/Model/FindSnapResDto.swift
  snaptime/Snaptime/Model/FindTagUserResDto.swift
Labels: ✨ new feature, Daehyun 🙋🏻‍♂️

#34 [Feat] 프로필 팔로우 버튼 설정 및 로그인 네트워크 로직 추가
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Auth/VCs/JoinEmailViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinIdViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinNameViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinPasswordViewController.swift
  snaptime/Snaptime/Auth/VCs/LoginViewController.swift
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Comment/View/SingleCommentView.swift
  snaptime/Snaptime/Components/APIService.swift
  snaptime/Snaptime/Components/TokenUtils.swift
  snaptime/Snaptime/Components/VCs/SnapViewController.swift
  snaptime/Snaptime/Components/Views/AlbumCollectionViewCell.swift
  snaptime/Snaptime/Components/Views/SnapCollectionViewCell.swift
  snaptime/Snaptime/Components/Views/SnapPreviewCollectionViewCell.swift
  snaptime/Snaptime/Components/Views/SnapTimeCustomButton.swift
  snaptime/Snaptime/Coordinator/AppCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Extension/UIViewController+.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Model/AccessToken.swift
  snaptime/Snaptime/Model/CommonResponseDtoListFindAllAlbumsResDto.swift
  snaptime/Snaptime/Model/CommonResponseDtoListFindFriendResDto.swift
  snaptime/Snaptime/Model/CommonResponseDtoSignInResDto.swift
  snaptime/Snaptime/Model/FindSnapResDto.swift
  snaptime/Snaptime/Model/ProfileBasicModel.swift
  snaptime/Snaptime/Model/SignInReqDto.swift
  snaptime/Snaptime/Model/UserProfileResDto.swift
  snaptime/Snaptime/Model/UserReqDto.swift
  snaptime/Snaptime/Model/UserResDto.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/FollowViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumListView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/AlbumListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/TagListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/FollowTableViewCell.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Profile/View/TagListView.swift
  snaptime/Snaptime/Profile/View/TopTapBarView.swift
Labels: ✨ new feature, Bowon 🙋🏻‍♀️
