Repository AppCenter-Snaptime/snaptime-iOS, pull requests merged in 2024-03, with the labels that each got.

#10 [Feat] AddAlbumView 구현중....
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Home/VCs/AddAlbumViewController.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Home/View/PreviewView.swift
  snaptime/Snaptime/Home/View/QRReaderView.swift
Labels: ✨ new feature, 📋 UI, Daehyun 🙋🏻‍♂️

#9 [Feat&Refactor] MyProfile화면 구성변경 및 EditProfile, SettingProfile 화면 구현
  snaptime/Podfile.lock
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Extension/UIColor+.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/MyProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumAndTagListView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/AlbumCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/EditProfileTextField.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileListTabButton.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileStatusButton.swift
  snaptime/Snaptime/Profile/View/CustomComponents/SettingTableViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/TagListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/TopTapBarCollectionViewCell.swift
  snaptime/Snaptime/SceneDelegate.swift
Labels: Bowon 🙋🏻‍♀️

#12 [Feat] profile 설정화면 구현
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Profile/VCs/MyProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumListView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/AlbumListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileSettingItemView.swift
  snaptime/Snaptime/Profile/View/CustomComponents/ProfileSettingView.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/SceneDelegate.swift
Labels: 📋 UI, Bowon 🙋🏻‍♀️

#14 [Feat] Community 첫 화면 UI 구현
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/community/VCs/CommunityViewController.swift
  snaptime/Snaptime/community/View/CommunityCollectionViewCell.swift
  snaptime/Snaptime/community/View/UserPostView.swift
Labels: 📋 UI, Daehyun 🙋🏻‍♂️

#13 [Feat] Notification 기능 UI 구현
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Components/CommentView.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/SceneDelegate.swift
  snaptime/Snaptime/community/VCs/NotificationViewController.swift
  snaptime/Snaptime/community/View/NotificationCollectionViewCell.swift
Labels: 📋 UI, Bowon 🙋🏻‍♀️
