Repository AppCenter-Snaptime/snaptime-iOS, pull requests merged in 2024-08, with the labels that each got.

#37 [Feat] 자동로그인 로직 추가 및 로그인 UI 변경 대응
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/AppDelegate.swift
  snaptime/Snaptime/Assets.xcassets/HeaderLogo.imageset/Contents.json
  snaptime/Snaptime/Assets.xcassets/HeaderLogo.imageset/HeaderLogo1.png
  snaptime/Snaptime/Assets.xcassets/HeaderLogo.imageset/HeaderLogo2.png
  snaptime/Snaptime/Assets.xcassets/HeaderLogo.imageset/HeaderLogo3.png
  snaptime/Snaptime/Assets.xcassets/SnapExample.imageset/snapmoon.jpeg
  snaptime/Snaptime/Assets.xcassets/Splash.imageset/LOGIN.png
  snaptime/Snaptime/Assets.xcassets/Splash.imageset/LOGIN2.png
  snaptime/Snaptime/Assets.xcassets/Splash.imageset/LOGIN3.png
  snaptime/Snaptime/Assets.xcassets/loginImage.imageset/Contents.json
  snaptime/Snaptime/Assets.xcassets/loginImage.imageset/loginImage1.png
  snaptime/Snaptime/Assets.xcassets/loginImage.imageset/loginImage2.png
  snaptime/Snaptime/Assets.xcassets/loginImage.imageset/loginImage3.png
  snaptime/Snaptime/Assets.xcassets/splash.imageset/Contents.json
  snaptime/Snaptime/Assets.xcassets/splash.imageset/splash1.png
  snaptime/Snaptime/Assets.xcassets/splash.imageset/splash2.png
  snaptime/Snaptime/Assets.xcassets/splash.imageset/splash3.png
  snaptime/Snaptime/Auth/VCs/JoinEmailViewController.swift
  snaptime/Snaptime/Auth/VCs/LoginViewController.swift
  snaptime/Snaptime/Auth/View/OAuthButton.swift
  snaptime/Snaptime/Base.lproj/LaunchScreen.storyboard
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Comment/View/SingleCommentView.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/KeyChain.swift
  snaptime/Snaptime/Components/TokenUtils.swift
  snaptime/Snaptime/Components/VCs/SnapViewController.swift
  snaptime/Snaptime/Components/Views/AlbumCollectionViewCell.swift
  snaptime/Snaptime/Components/Views/AlbumSelectCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/AppCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Coordinator/TabBarCoordinator.swift
  snaptime/Snaptime/Extension/UIButton+.swift
  snaptime/Snaptime/Extension/UIViewController+.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Model/CommonResponseDtoListFindSnapPagingResDto.swift
  snaptime/Snaptime/Model/CommonResponseDtoSignInResDto.swift
  snaptime/Snaptime/Model/FindParentReplyResDto.swift
  snaptime/Snaptime/Model/FindSnapResDto.swift
  snaptime/Snaptime/Model/ProfileBasicModel.swift
  snaptime/Snaptime/Model/ProfileBasicUserDefaults.swift
  snaptime/Snaptime/Network/APIInterceptor.swift
  snaptime/Snaptime/Network/APIService.swift
  snaptime/Snaptime/Profile/VCs/FollowViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/CustomComponents/AlbumListCollectionViewCell.swift
  snaptime/Snaptime/Profile/View/FollowTableViewCell.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/SceneDelegate.swift
Labels: ✨ new feature, 📋 UI, Bowon 🙋🏻‍♀️

#39 [Feat] 스냅 수정, 삭제 네트워크 로직 적용
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/VCs/SnapViewController.swift
  snaptime/Snaptime/Components/Views/SnapCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Network/APIService.swift
Labels: ✨ new feature, Daehyun 🙋🏻‍♂️

#38 [Feat] 유저 검색 기능 추가 및 회원가입 로직 추가
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Auth/VCs/JoinEmailViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinIdViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinNameViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinPasswordViewController.swift
  snaptime/Snaptime/Auth/VCs/LoginViewController.swift
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Community/VCs/SearchViewController.swift
  snaptime/Snaptime/Community/View/SearchResultCollectionViewCell.swift
  snaptime/Snaptime/Components/VCs/BaseViewController.swift
  snaptime/Snaptime/Components/VCs/CustomAlertViewController.swift
  snaptime/Snaptime/Components/VCs/SnapPreviewViewController.swift
  snaptime/Snaptime/Coordinator/AuthCoordinator.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Extension/String+.swift
  snaptime/Snaptime/Model/SignUpReqDto.swift
  snaptime/Snaptime/Model/UserFindResDto.swift
  snaptime/Snaptime/Model/UserPagingResDto.swift
  snaptime/Snaptime/Network/APIService.swift
  snaptime/Snaptime/Profile/VCs/FollowViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Profile/View/TagListView.swift
  snaptime/Snaptime/Profile/View/TopTapBarView.swift
Labels: ✨ new feature, 📋 UI, Bowon 🙋🏻‍♀️

#41 [Feat] 스냅 앨범 이동 기능, 스냅 생성시 앨범 선택 화면 구현
  snaptime/Snaptime/Components/VCs/SnapViewController.swift
  snaptime/Snaptime/Components/Views/AlbumSelectCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/CommunityCoordinator.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Coordinator/ProfileCoordinator.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Home/VCs/SelectAlbumViewController.swift
  snaptime/Snaptime/Network/APIService.swift
Labels: ✨ new feature, Daehyun 🙋🏻‍♂️

#40 [Feat] 로그인 네트워크 indicatorView 추가 및 커뮤니티 Pagination(무한 스크롤) 기능 추가
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/Auth/VCs/JoinEmailViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinIdViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinNameViewController.swift
  snaptime/Snaptime/Auth/VCs/JoinPasswordViewController.swift
  snaptime/Snaptime/Auth/VCs/LoginViewController.swift
  snaptime/Snaptime/Auth/View/AuthTextField.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Components/KeyChain.swift
  snaptime/Snaptime/Coordinator/AuthCoordinator.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Model/CommonMsgRes.swift
  snaptime/Snaptime/Model/ModifyUserInfoResDto.swift
  snaptime/Snaptime/Model/UserFindResDto.swift
  snaptime/Snaptime/Network/APIService.swift
  snaptime/Snaptime/Network/LoadingService.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
Labels: ✨ new feature, Bowon 🙋🏻‍♀️

#42 [Refactor] 네트워크 코드 리팩토링
  snaptime/Snaptime.xcodeproj/project.pbxproj
  snaptime/Snaptime/AppDelegate.swift
  snaptime/Snaptime/Auth/VCs/JoinIdViewController.swift
  snaptime/Snaptime/Auth/VCs/LoginViewController.swift
  snaptime/Snaptime/Comment/VCs/CommentViewController.swift
  snaptime/Snaptime/Comment/View/SingleCommentView.swift
  snaptime/Snaptime/Community/VCs/CommunityViewController.swift
  snaptime/Snaptime/Community/VCs/NotificationViewController.swift
  snaptime/Snaptime/Community/VCs/SearchViewController.swift
  snaptime/Snaptime/Components/VCs/SnapPreviewViewController.swift
  snaptime/Snaptime/Components/VCs/SnapViewController.swift
  snaptime/Snaptime/Components/Views/SnapCollectionViewCell.swift
  snaptime/Snaptime/Coordinator/HomeCoordinator.swift
  snaptime/Snaptime/Home/VCs/AddSnapViewController.swift
  snaptime/Snaptime/Home/VCs/MainAlbumViewController.swift
  snaptime/Snaptime/Home/VCs/SelectAlbumViewController.swift
  snaptime/Snaptime/Home/VCs/SnapTagListViewController.swift
  snaptime/Snaptime/Model/CommonResDtoVoid.swift
  snaptime/Snaptime/Network/APIInterceptor.swift
  snaptime/Snaptime/Network/APIService.swift
  snaptime/Snaptime/Profile/VCs/EditProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/FollowViewController.swift
  snaptime/Snaptime/Profile/VCs/ProfileViewController.swift
  snaptime/Snaptime/Profile/VCs/SettingProfileViewController.swift
  snaptime/Snaptime/Profile/View/AlbumListView.swift
  snaptime/Snaptime/Profile/View/FollowTableViewCell.swift
  snaptime/Snaptime/Profile/View/ProfileStatusView.swift
  snaptime/Snaptime/Profile/View/TagListView.swift
Labels: 🧑🏻‍🔧 refactoring, Bowon 🙋🏻‍♀️
